version: '3.4'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - mysql
      - redis
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DB_PORT: 3306
      DB_HOST: mysql

  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql

  redis:
    image: "redis:6.0.8"
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - '6379:6379'

volumes:
  data:
  redis:
